### ISSUE TITLE
Not working with iOS 10 SDK and Xcode 8

### ISSUE THREAD

**Issue by karan1149** [enchev/nativescript-screenshot#3]
Upon trying to take a picture after installing Xcode 8, I get the following error every time on iOS: 

 CONSOLE LOG file:///app/tns_modules/@angular/core/src/facade/lang.js:360:16: share@file:///app/tns_modules/nativescript-social-share/social-share.js:16:33
    shareImage@file:///app/tns_modules/nativescript-social-share/social-share.js:22:8
    takePicture@file:///app/pages/stats/stats.component.js:87:31
    file:///app/pages/stats/stats.component.js:77:30
    invoke@file:///app/tns_modules/zone.js/dist/zone-node.js:281:34
    onInvoke@file:///app/tns_modules/@angular/core/src/zone/ng_zone_impl.js:53:47
    invoke@file:///app/tns_modules/zone.js/dist/zone-node.js:280:43
    runGuarded@file:///app/tns_modules/zone.js/dist/zone-node.js:188:54
    file:///app/tns_modules/zone.js/dist/zone-node.js:164:40
    tick@file:///app/tns_modules/timer/timer.js:17:26
    UIApplicationMain@[native code]
    start@file:///app/tns_modules/application/application.js:234:26
    nativeScriptBootstrap@file:///app/tns_modules/nativescript-angular/application.js:144:22
    anonymous@file:///app/main.js:7:36
    evaluate@[native code]
    moduleEvaluation@[native code]
    [native code]
    promiseReactionJob@[native code]
Sep 23 01:12:23 Karans-MBP-3 squadstats[5174]: 1   0x110030379 NativeScript::FFICallbackNativeScript::ObjCMethodCallback::ffiClosureCallback(ffi_cif_, void_, void*_, void_)
Sep 23 01:12:23 Karans-MBP-3 squadstats[5174]: 2   0x11069d51e ffi_closure_unix64_inner
Sep 23 01:12:23 Karans-MBP-3 squadstats[5174]: 3   0x11069ded2 ffi_closure_unix64
Sep 23 01:12:23 Karans-MBP-3 squadstats[5174]: 4   0x113964964 **CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION**
Sep 23 01:12:23 Karans-MBP-3 squadstats[5174]: 5   0x1139645f3 __CFRunLoopDoTimer
Sep 23 01:12:23 Karans-MBP-3 squadstats[5174]: 6   0x11396417a __CFRunLoopDoTimers
Sep 23 01:12:23 Karans-MBP-3 squadstats[5174]: 7   0x11395bf01 __CFRunLoopRun
Sep 23 01:12:23 Karans-MBP-3 squadstats[5174]: 8   0x11395b494 CFRunLoopRunSpecific
Sep 23 01:12:23 Karans-MBP-3 squadstats[5174]: 9   0x115834a6f GSEventRunModal
Sep 23 01:12:23 Karans-MBP-3 squadstats[5174]: 10  0x1111f2f34 UIApplicationMain
Sep 23 01:12:23 Karans-MBP-3 squadstats[5174]: 11  0x11069dd2d ffi_call_unix64
Sep 23 01:12:23 Karans-MBP-3 squadstats[5174]: 12  0x1323f4170
Sep 23 01:12:23 Karans-MBP-3 squadstats[5174]: file:///app/tns_modules/rxjs/Subscriber.js:229:22: JS ERROR TypeError: UIApplication.sharedApplication is not a function. (In 'UIApplication.sharedApplication()', 'UIApplication.sharedApplication' is an instance of UIApplication)
Sep 23 01:12:23 Karans-MBP-3 com.apple.CoreSimulator.SimDevice.7FCBF1A7-A9BF-4A5A-8DFE-015253F199B4.launchd_sim[4300](UIKitApplication:org.nativescript.squadstats[0x97f1][5174]): Service exited due to Segmentation fault: 11

**Comment by ghost** [comment]
`UIApplication.sharedApplication' is an instance of UIApplication`

@karan1149 This is an issue with the rxjs module, not this plugin, it needs to use `utils.ios.getter`.

@enchev Can you close this?
